<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>

    <!-- NuGet 패키지 메타데이터 -->
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>H00N.ObservableValue</PackageId>
    <Version>0.1.5</Version>
    <Authors>SEH00N</Authors>
    <Company></Company>
    <Product>H00N.ObservableValue</Product>
    <Description>Attribute-based observable field to property generator for C#.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/SEH00N/H00N.ObservableValue</PackageProjectUrl>
    <RepositoryUrl>https://github.com/SEH00N/H00N.ObservableValue</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>csharp;source-generator;observable;unity</PackageTags>
    <IncludeSymbols>false</IncludeSymbols>
    <IncludeSource>false</IncludeSource>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\\ObservableValue.Generator\\bin\\$(Configuration)\\netstandard2.0\\ObservableValue.Generator.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\\..\\README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
